name: Terraform Apply

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify the Terraform version you need

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Specify your AWS region

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Plan Terraform
        working-directory: infra
        run: terraform plan

      - name: Apply Terraform
        working-directory: infra
        run: terraform apply
        env:
          TF_INPUT: "true"  # Prompt for manual approval
