name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approval required after reviewing Terraform destroy plan. Type "yes" to approve.'
        required: true

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify the Terraform version you need

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your AWS region

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

     - name: Plan Terraform Destroy
        working-directory: infra
        run: terraform plan -destroy -out=destroy.tfplan

      - name: Display Terraform Destroy Plan
        working-directory: infra
        run: terraform show destroy.tfplan

      - name: Wait for manual approval
        run: |
          echo "Waiting for manual approval..."
          sleep 300  # Wait for 5 minutes for manual approval

      - name: Check approval
        id: check-approval
        run: |
          if [ "${{ github.event.inputs.approve }}" != "yes" ]; then
            echo "Approval not granted. Exiting."
            exit 1
          fi

      - name: Destroy Terraform
        if: ${{ steps.check-approval.outcome == 'success' }}
        working-directory: infra
        run: terraform apply -destroy -auto-approve destroy.tfplan

      - name: Destroy Terraform
        if: ${{ steps.check-approval.outcome == 'success' }}
        working-directory: infra
        run: terraform destroy -auto-approve
