name: this is my first github action workflow

on:
    workflow_dispatch: 
     inputs:
      logLevel:
        description: 'cheking with true and false'
        required: true
        default: true
        type: boolean


env:
    name: john

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo ${{ env.name }}
            
            - name: checking context
              run: echo "the repository is ${{ github.repository }}"

            - name: checking runner context
              run: echo "the repository is ${{ runner.arch}}"

            - name: checking secrets context-2
              run: echo "the repository is ${{ secrets.GITHUB_TOKEN}}"
