name: this is my first github action workflow

on:
    push: 
        branches: main

env:
    name: john

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo ${{ env.name }}
